<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>CryptoJournal.Wpf.ico</ApplicationIcon>

	<AssemblyTitle>CryptoJournal</AssemblyTitle>
	<Description>Cryptocurrency portfolio management app</Description>
	<Company>ButterDevelop</Company>
	<Product>CryptoJournal.Wpf</Product>
	<Copyright>© ButterDevelop 2026</Copyright>

	<Version>1.0.1</Version>

	<RepositoryUrl>https://github.com/ButterDevelop/CryptoJournal.Wpf</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
	  <_Parameter1>RepositoryUrl</_Parameter1>
	  <_Parameter2>https://github.com/ButterDevelop/CryptoJournal.Wpf</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\default_coin.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="CryptoJournal.Wpf.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc5.4" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1-ci1190" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1-ci1190" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\default_coin.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
